# Generated by Django 4.2.1 on 2023-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eng_URL', models.URLField()),
                ('Eng_Status', models.BooleanField(default=False)),
                ('Eng_Content', models.CharField(max_length=20)),
                ('Hindi_URL', models.URLField()),
                ('Hindi_Status', models.BooleanField(default=False)),
                ('Hindi_Content', models.CharField(max_length=20)),
                ('Marathi_URL', models.URLField()),
                ('Marathi_Status', models.BooleanField(default=False)),
                ('Marathi_Content', models.CharField(max_length=20)),
                ('Bengali_URL', models.URLField()),
                ('Bengali_Status', models.BooleanField(default=False)),
                ('Bengali_Content', models.CharField(max_length=20)),
                ('Kannada_URL', models.URLField()),
                ('Kannada_Status', models.BooleanField(default=False)),
                ('Kannada_Content', models.CharField(max_length=20)),
                ('Malayalam_URL', models.URLField()),
                ('Malayalam_Status', models.BooleanField(default=False)),
                ('Malayalam_Content', models.CharField(max_length=20)),
                ('Manipuri_URL', models.URLField()),
                ('Manipuri_Status', models.BooleanField(default=False)),
                ('Manipuri_Content', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Domain Information',
            },
        ),
    ]
