# Generated by Django 4.2.1 on 2023-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain_information',
            name='Bengali_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Eng_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Hindi_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Kannada_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Malayalam_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Manipuri_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Marathi_URL',
            field=models.URLField(blank=True),
        ),
    ]
