# Generated by Django 4.2.1 on 2023-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_domain_information_bengali_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain_information',
            name='Bengali_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Bengali_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Eng_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Eng_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Hindi_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Hindi_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Kannada_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Kannada_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Malayalam_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Malayalam_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Manipuri_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Manipuri_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Marathi_Content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domain_information',
            name='Marathi_URL',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
